### ISSUE TITLE
Hacktoberfest Issue Thread [Social Media Analytics]

### ISSUE THREAD

**Issue by rtd62** [rtd62/facebook-insights#1]
Hello [Hacktoberfest](https://hacktoberfest.digitalocean.com/) contributors! I have here a web application that needs some work, and I wanted some help! This will be a great opportunity for you guys to receive the shirt and stickers for this event! I wanted to make this issue to serve a discussion thread for tasks related to the project.

### Allow me to explain a little about the app:

Last year, I was working on a web application project that needed to use the Facebook Graph API to grab Insights from a user's Page that they manage. Particularly, in this case, the Page's **follower count**. I wanted to be able to pull the Insights, display the data from the API, and be able to save that to a database, and eventually display it in a nice graph.
After tons of searching through repos here on GitHub, I was able to fork an old project from three years ago called [SMA](https://github.com/Tudor-B/SMA). I wanted to be able to build on this so that developers in the future could benefit as well.

### I have a list of things that I would like to be able to fix/implement - such as:

- [ ] Updating to the current API version
- [x] Request authentication from user to show a list of their Pages they manage
- [x] Show those Pages in a list to select which they want their Insights from
- [ ] Display Insights on the web page in the form of a list
- [ ] Save the data to a database [any type of database works at the moment]
- [ ] Display the data in an analytics-style graph

**If you are a beginner contributor**: On this thread, ask any questions that you may have! These can be about the project as a whole, how to find issues, how to create well-organized merge requests, etc.
**If you are a veteran contributor**: Please comment any issues you think would be a good project for beginners!

Thank you to everyone who is willing to support me in this project! Happy Hacktoberfest!

**Comment by xepozz** [comment]
Hello, I want to help you.
Please, use a composer instead of require_once

**Comment by rtd62** [comment]
Loved the code restructure here @xepozz - let's keep working together and if you have any ideas for features, let me know!

**Comment by xepozz** [comment]
ok, i suggest use a framework because in future will be more easily write code and support project
i am suggest my loved framework Yii2

**Comment by rtd62** [comment]
@xepozz `Yii2` works for me - it's very similar to `Laravel`. As well, I looked deeper into the code structure and the API is version `2.2` ... really outdated and no longer supported. It has to be remastered from the ground up on the current `2.10`. And I dug deeper into the docs, and it looks like it's easier to use the JavaScript SDK rather than the PHP SDK. Your thoughts?

**Comment by xepozz** [comment]
@rtd62 we can use NodeJS and any framework eg React or Angular

**Comment by rtd62** [comment]
I'm familiar with NodeJS and Angular @xepozz -- if you think that is the best solution, then let's go for it

**Comment by xepozz** [comment]
Do you use any messangers?

**Comment by rtd62** [comment]
@xepozz Yeah, I use WhatsApp -- add me by searching the number 863-212-6774

**Comment by sajeetharan** [comment]
is this implemented?

**Comment by rtd62** [comment]
@sajeetharan @xepozz 
 I'm actually probably just going to open a repo that builds this app from the current API `v2.10` -- the code and SDK used here is old and unsalvagable. I also have not had as much time as I thought to work on this in the past week.

**Comment by rtd62** [comment]
@sajeetharan @xepozz 
Here is a link to the new repo -> [facebook-insights-2.10](https://github.com/rtd62/facebook-insights-2.10)

**Comment by xepozz** [comment]
@rtd62 i can't find you

**Comment by rtd62** [comment]
@xepozz Strange... that's the number I have linked.. maybe the account is either `Robert Dewitt` or `rtd62` -- sorry, I don't know how to share my WhatsApp contact
